<?php
 // module/Album/view/album/album/edit.phtml:

use Album\Model\Album;

 $title = 'Edit album';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'album',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('title'));
 echo $this->formRow($form->get('artist'));
 echo $this->formRow($form->get('email'));
 echo $this->formRow($form->get('release_date'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();